---
title: The Innovation District of Chattanooga
timezone: America/New_York
collections:
  directory_categories:
    title: Directory Categories
    output: false
  directory_filters:
    title: Directory Filters
    output: false
  directory_members:
    title: Directory Members
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: directory_members
  values:
    Directory Categories: []
    Directory Filters: []
    member:
      name: 
      bio: 
      address: 
      url: 
description: The first mid-sized city to designate an innovation district.
baseurl: 
facebook: https://www.facebook.com/InnovationDistrictCHA/
twitter: https://twitter.com/ChattanoogaID
address: The Enterprise Center <br>1100 Market Street, Suite 500 <br>Chattanooga,
  TN 37402
phone_number: "(423) 661-3300"
email: enterprisecenter@theenterprisectr.org
about_us_blurb: Chattanooga is the first mid-sized city with an established innovation
  district. Larger cities such as Boston, Washington DC, and Barcelona already enjoy
  the community benefits that come from designing spaces specifically for workers
  and companies in the new knowledge economy.
url: https://www.chainnovate.com/
permalink: "/:title/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
