---
title: Society of Work
timezone: America/New_York
collections:
  members:
    title: Members
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    image: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: members
  values:
    first_name: 
    link: 
    link_text: 
    content: Nothing goes here
    image: 
    crazy_image: 
    position: 
    title: Replace with first and last name // for admin reference
    company: 
description: Society of Work is a shared coworking space in Chattanooga, TN with business
  flexibility in mind and resources to help like-minded people connect and create
  amazing things together.
baseurl: 
facebook: https://www.facebook.com/SocietyOfWork
twitter: https://twitter.com/SocietyofWork
instagram: http://instagram.com/societyofwork
linkedin: https://www.linkedin.com/company/society-of-work
tagline: Connect. Create. Cowork.
footer_news_letter_cta: Subscribe to our newsletter
footer_news_letter_description: Get the latest events and SoW news in your inbox.
logo: "/assets/img/logo/red-sow-logo.svg"
address: 1100 Market Street, Floor 6, Chattanooga, TN 37402
phone_number: 423-449-9112
url: https://www.societyofwork.com
pricing_section:
  header: Pricing Plans
  blurb: For individuals, startups, and small teams with month-to-month flexibility.
  plans:
  - plan: 
    name: Day Pass
    price: 25
    additional_info: Includes Everything
  - plan: 
    name: Community Desks
    price: 150
    additional_info: No long term contract
  - plan: 
    name: Reserved Desk
    price: 350
    additional_info: No long term contract
  - plan: 
    name: Private Office
    price: 550
    additional_info: 6mo lease / month to month after
permalink: "/:title/"
markdown: kramdown
cloudinary:
  cloud_name: 
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 2000
      fallback_max_width: 1300
      steps: 5
      sizes: "(min-width: 1100px) 957px, 100vw"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-cloudinary
