---
title: The Innovation District of Chattanooga
timezone: UTC
collections:
  directory_members:
    title: Directory Members
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: directory_members
  values:
    member_categories: ["Startup Support", "Arts & Culture", "Social Enterprise", "Business Development", "Collision Points", "Civic & Public", "Tech & Design"]
    member_filters: ["Funding", "Mentoring", "Training", "Networking", "Workspace"]
    member:
      name: 
      bio: 
      address: 
      url: 
description: The first mid-sized city to designate an innovation district.
baseurl: ''
url: https://www.chainnovate.com/
permalink: "/:title/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
