---
title: The Enterprise Center
timezone: America/New_York
collections:
  blog_authors:
    title: Blog Authors
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: blog_authors
  values:
    image: 
- scope:
    path: ''
    type: pages
  values:
    header:
      image: 
- scope:
    path: ''
    type: posts
  values:
    Blog Author: 
    featured_image: 
    image_description_for_the_visually_impaired: 
    bottom_button_link: 
    bottom_button_text: 
description: Establishing Chattanooga as a hub of innovation, improving people’s lives
  by leveraging the city’s digital technology to create, demonstrate, test, and apply
  solutions for the 21st century.
baseurl: https://www.theenterprisectr.org/
facebook: https://www.facebook.com/theenterprisectr/
twitter: 
logo: "/assets/img/logo/full-logo.svg"
address: The Enterprise Center <br>1100 Market Street, Suite 500 <br>Chattanooga,
  TN 37402
phone_number: "(423) 661-3300"
email: enterprisecenter@theenterprisectr.org
footer_about_blurb: Chattanooga is the first mid-sized city with an established innovation
  district. Larger cities such as Boston, Washington DC, and Barcelona already enjoy
  the community benefits that come from designing spaces specifically for workers
  and companies in the new knowledge economy.
url: https://www.chainnovate.com/
permalink: "/:title/"
markdown: kramdown
cloudinary:
  cloud_name: the-enterprise-center
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 2000
      fallback_max_width: 1300
      steps: 5
      sizes: "(min-width: 1100px) 957px, 100vw"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
- gulpfile.js
- _assets
gems:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-cloudinary
